GET http://localhost:5000/movies/
Accept: application/json

###
GET http://localhost:5000/movies/10
Accept: application/json

###
GET http://localhost:5000/movies/?director_id=2
Accept: application/json

###
GET http://localhost:5000/movies/?genre_id=4
Accept: application/json

###
GET http://localhost:5000/movies/?genre_id=4&director_id=2
Accept: application/json

###
POST http://localhost:5000/movies/
Content-Type: application/json

{
  "id": 28,
  "title": "title",
  "description": "description",
  "trailer": "trailer",
  "year": 1222,
  "rating": 1,
  "genre_id": 1,
  "director_id": 1
}

###
PUT http://localhost:5000/movies/10
Accept: application/json
Content-Type: application/json

{
  "title": "GOVerNOr",
  "description": "description2",
  "trailer": "trailer",
  "year": 2222,
  "rating": 1,
  "genre_id": 4,
  "director_id": 5
}

###
DELETE http://localhost:5000/movies/28
Accept: application/json

###
PATCH http://localhost:5000/movies/1
Accept: application/json
Content-Type: application/json

{
  "title": "DA"
}

###